CREATE TABLE BOARD(
  id BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(200) NOT NULL,
  CONTENT VARCHAR(200),
  NAME VARCHAR(200) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE MEMBER(
    id BIGINT NOT NULL AUTO_INCREMENT,
    MEMBER_ID VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
)